L_IM_SETTING_TITLE = "Messenger"
L_IM_SETTING_ALERTS_SUBTITLE = "Change Messenger alerts"
L_IM_SETTING_ALERTS_MSG1 = "MSN TV can show you an alert each time one of your Messenger contacts comes online. Choose <b>Show me Messenger alerts</b>."
L_IM_SETTING_ALERTS_MSG2 = "Show me Messenger alerts"
L_IM_SETTING_ALERTS_MSG3 = "Don’t show me Messenger alerts"
L_IM_SETTING_ALERTS_MSG4 = "You may not want to be interrupted by alerts when you are watching full-screen videos or slideshows. Choose the link below."
L_IM_SETTING_ALERTS_MSG5 = "Turn off alerts during videos and slideshows"